version: "3.3"
services:
  npm:
    entrypoint: "npm run"
    image: node:latest
    volumes:
      - ./:/home/node/
    working_dir: /home/node/
  web:
    entrypoint: "npm start"
    image: node:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/
    working_dir: /home/node/
