version: "3.3"
services:
  npm:
    entrypoint: "npm"
    image: node:latest
    volumes:
      - ./:/home/node/
    working_dir: /home/node/
  web:
    entrypoint: "npm start"
    image: node:latest
    ports:
      - 6060:6060
    volumes:
      - ./:/home/node/
    working_dir: /home/node/
