import faker from 'faker'; // eslint-disable-line import/no-extraneous-dependencies

export default [
  {
    id: 1,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 2,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 3,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 4,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 5,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 6,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 7,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 8,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 9,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 10,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 11,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 12,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 13,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 14,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 15,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 16,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 17,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 18,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 19,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
  {
    id: 20,
    accountName: faker.finance.accountName(),
    department: faker.commerce.department(),
    pastDate: faker.date.past(),
    futureDate: faker.date.future(),
    fulName: faker.name.firstName() + faker.name.lastName(),
    jobDescriptor: faker.name.jobDescriptor(),
    productName: faker.commerce.productName(),
  },
];
