export default [
  {
    id: 1,
    title: 'Site Planning',
    status: 'Completed',
    tags: ['Management', 'Sales'],
    assignees: ['Lynda Newton'],
    startDate: 'Jul 2, 2018',
    endDate: 'Jul 5, 2018',
    percent: 100,
  },
  {
    id: 2,
    title: 'Analysis of Requirements',
    status: 'Completed',
    tags: ['Management', 'Sales'],
    assignees: ['Lynda Newton'],
    startDate: 'Jul 5, 2018',
    endDate: 'Jul 8, 2018',
    percent: 100,
  },
  {
    id: 3,
    title: 'Create',
    status: 'Completed',
    tags: ['Management', 'Sales'],
    assignees: ['Multiple'],
    startDate: 'Jul 8, 2018',
    endDate: 'Jul 15, 2018',
    percent: 100,
  },
  {
    id: 4,
    title: 'Page Assignment',
    status: 'Completed',
    tags: ['Management', 'Sales'],
    assignees: ['Multiple'],
    startDate: 'Jul 15, 2018',
    endDate: 'Jul 22, 2018',
    percent: 100,
  },
  {
    id: 5,
    title: 'Asset Assignments',
    status: 'Completed',
    tags: ['Design', 'Management'],
    assignees: ['Chris Base'],
    startDate: 'Jul 15, 2018',
    endDate: 'Jul 22, 2018',
    percent: 100,
  },
  {
    id: 6,
    title: 'Page Design Planning',
    status: 'Started',
    tags: ['Research', 'Design'],
    assignees: ['Multiple'],
    startDate: 'Jul 18, 2018',
    endDate: 'Jul 23, 2018',
    percent: 75,
  },
  {
    id: 7,
    title: 'Define Needs',
    status: 'Started',
    tags: ['Research'],
    assignees: ['Elizabeth Alvarez'],
    startDate: 'Jul 18, 2018',
    endDate: 'Jul 23, 2018',
    percent: 60,
  },
  {
    id: 8,
    title: 'Define Problem',
    status: 'Needs Info',
    tags: ['Research', 'Design'],
    assignees: ['Multiple'],
    startDate: 'Jul 18, 2018',
    endDate: 'Jul 23, 2018',
    percent: 55,
  },
  {
    id: 9,
    title: 'First Mockup',
    status: 'Started',
    tags: ['Design'],
    assignees: ['Chris Base'],
    startDate: 'Jul 18, 2018',
    endDate: 'Aug 3, 2018',
    percent: 100,
  },
  {
    id: 10,
    title: 'Implement Client Feedback',
    status: 'Not Started',
    tags: ['Design', 'Development'],
    assignees: ['Multiple'],
    startDate: 'Aug 3, 2018',
    endDate: 'Aug 10, 2018',
    percent: 0,
  },
  {
    id: 11,
    title: 'Upload Site to Staging & Route to Client',
    status: 'Not Started',
    tags: ['Development'],
    assignees: ['Billy Vandergantt'],
    startDate: 'Aug 8, 2018',
    endDate: 'Sep 7, 2018',
    percent: 0,
  },
  {
    id: 12,
    title: 'Implement Client Feedback',
    status: 'Not Started',
    tags: ['Design'],
    assignees: ['Chris Base'],
    startDate: 'Sep 7, 2018',
    endDate: 'Sep 14, 2018',
    percent: 0,
  },
  {
    id: 13,
    title: 'Site Go Live',
    status: 'Not Started',
    tags: ['Development'],
    assignees: ['Billy Vandergantt'],
    startDate: 'Sep 14, 2018',
    endDate: 'Sep 16, 2018',
    percent: 0,
  },
  {
    id: 14,
    title: 'Report on post-launch performance',
    status: 'Not Started',
    tags: ['Management', 'Business Dev'],
    assignees: ['Multiple'],
    startDate: 'Sep 16, 2018',
    endDate: 'Sep 23, 2018',
    percent: 0,
  },
];
