version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - gh-pages

executors:
  node:
    docker:
      - image: circleci/node:8.15


jobs:
  build_and_test:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
          - node_modules-2-{{ checksum "package.json" }}
          - node_modules-2-
      - run: npm ci
      - save_cache:
          paths:
            - $HOME/.npm
          key: node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
      - run: npm run lint
      - run: npm test
